### ISSUE TITLE
Big files are bad

### ISSUE THREAD

**Issue by Andonome** [passamo9/LaTeX_EnglandWales_Templates#19]
Git can't track files which aren't in plain text, such as the pdfs and .docx files.  As these files update, the repo will become ungainly.

The standard solution is to install a large file server (lfs), which only gives people the latest version of these documents, rather than every version every used.  Unfortunately the free version of github doesn't provide this for public forks, so I've pushed the repo to gitlab, here:

https://gitlab.com/andonome/latex_englandwales_templates/-/tree/lfs

Users on Windows with the Github desktop app will already have git-lfs functionality in their app.

Linux and Mac users will have to install the package `git-lfs` via their package manager.

If you'd like to pull this branch to your local repo, you can add this gitlab page as a new remote:

> git remote add gitlab https://gitlab.com/andonome/latex_englandwales_templates.git

(this is pretty low priority, so if this is too much git for one day, just ignore this issue - it's trivial to redo this work later)

**Comment by passamo9** [comment]
Thanks @Andonome!

Perhaps @yjyao can help me with this.

**Comment by yjyao** [comment]
for the compiled PDFs we are working on it in #18.

was going to say this about the .docx files. i don't think they are there to be "tracked," more like tasks for contributors to work on. so i guess we won't even need an lfs for this. we can maybe just attach the .docx files to issues. for example:

> ISSUE support pleading titles
> reference attached .docx to create commands to make titles for pleading docs.
> [attached file: Example-Pleading.docx (256KB)]

**Comment by bond7o6** [comment]
If we're keeping this on Github with the CI, perhaps this could be closed?

**Comment by yjyao** [comment]
> perhaps this could be closed?

what do we want to do with the .docx files tho?

**Comment by bond7o6** [comment]
They aren't being updated, don't need diffs on them, and as we complete features we would probably want to move them out of the repo. I liked your idea of having them attached to issues, though perhaps wait till we complete the ones we have already. Discussed more at [.docx PR](https://github.com/passamo9/LaTeX_EnglandWales_Templates/pull/24#issuecomment-779415477).

**Comment by yjyao** [comment]
ok then. closing.
