### ISSUE TITLE
Opinion Section Headings

### ISSUE THREAD

**Issue by passamo9** [passamo9/LaTeX_EnglandWales_Templates#32]
Hi everyone. Thank you so much for the quality of the work and the speed at which you are all working. It's really inspiring

I am currently testing out the opinion.tex by transcribing an opinion I wrote last week. Because of the subject matter of the opinion, the headings are not just Introduction, Facts, Subsection 1, Subsubsection 2, like in the template.

In the example folder, I saw that there were several opinion.something files. I saw that the headings are set up in opinion.aux. I am happy to change them as I go along with (in this case) transcribing the opinion I wrote last week.

However, as an example, tomorrow I want to work on another opinion (call it NewOpinion), with different headings.

Do I copy all the opinion files into a new folder, NewOpinion, and make edits as necessary there?

Thanks so much!

**Comment by bond7o6** [comment]
You really shouldn't be editing any of the files that aren't `.tex` or `.bib` (if a `.bib` is ever needed). All the files that are `opinion.***` are temporary files that LaTeX uses to build the PDF, so they get overwritten the next time you run LaTeX on the `.tex` file. If you want to change the sections, you can just add `\subsection{the section name}` where you want the section in the `.tex` file. 

In the opinion file, `\section{something}` gives you a top level heading that is completely capitalised, like facts or introduction; `\subsection{something}` gives you a second level heading that appears the same to `\section{}` except it isn't completely capitalised; `\subsubsection{something}` gives you a third level heading that isn't bolded. If you want these changed, like you want to use lowercase letters in top level headings, please make an issue about and it'll get addressed at some point.

If you were writing a new document with the opinion template (note this will change once everything is grouped under a class), the `.tex` file should look something like:
```latex
\documentclass[a4paper,12pt]{article}
\usepackage{../engwales-opinion}

\usepackage[margin=2.5cm]{geometry}%% This is to determine margins
%\usepackage{blindtext}%% This is just to create lorem ipsums, you can remove this line

\title{An Opinion Written For a Client}%% any title you want, will appear in the pdf
\author{A. Barrister}%% this appears in the end signature 
\date{\today}%% This doesn't appear in the document, but is nice to keep track of the date

\begin{document}
\maketitle

\intro%% you can take this out if you don't need it
\begin{point}
  A paragraph of your choosing
\end{point}
\facts%% same for this
\begin{point}
  Any singular paragraph you enclose in this environment gets numbered correctly
\end{point}
\section{A heading}%% you can put these where ever you want first level headings
\begin{point}
  with paragraphs under them, if you want
\end{point}
\subsection{This is changable}%% place these where ever you want second level headings
\subsubsection{so is this}
\begin{point}
  more paragraphs
\end{point}
\signature%% place this where ever you want the signature to go, or omit it completely
\end{document}
```

You need to keep `engwales-opinion.sty` one directory below the .tex file, or change the `\usepackage{../engwales-opinion}` line to `\usepackage{./engwales-opinion}` and keep it in the same directory. Within your LaTeX editor, run latex on the `.tex` file and it should make your PDF. Any other questions, or issues?

**Comment by yjyao** [comment]
adding to that, please don't commit to main with experiment .tex files. if you'd like to get our help/review, make a pull request and ping us.

**Comment by passamo9** [comment]
>adding to that, please don't commit to main with experiment .tex files. if you'd like to get our help/review, make a pull request and ping us.

Is this referring to me? I don't fully understand what you are referring to. Sorry if I keep asking stupid questions

**Comment by passamo9** [comment]
>`\section{A heading}%% you can put these where ever you want first level headings`

Yes, this worked great!

**Comment by bond7o6** [comment]
I take it the issue is fixed? Perhaps close this if it is?

**Comment by passamo9** [comment]
Yes, let's close
